window.MARBELLA_PROPERTY_DATA = [
  {
    code: "K1",
    slug: "k1-duplex-puerto-banus-penthouse",
    path: "properties/k1-duplex-puerto-banus-penthouse.html",
    title: "Duplex Puerto Banus Penthouse",
    bookingTitle: "Duplex Puerto Banus Penthouse Apart K1",
    type: "Apartment",
    bookingUrl: "https://marbellapuertobanus.holidayfuture.com/listings/350049",
    source: "Direct booking page",
    guests: "5 guests",
    bedrooms: "2 bedrooms",
    bathrooms: "2 bathrooms",
    beds: "3 double beds",
    rating: "4.85",
    reviews: "6 reviews",
    imageCount: "25 photos",
    summary:
      "A modern duplex penthouse on the first line of Puerto Banus, with marina views from two terraces and an easy walk to restaurants, bars, shopping, the promenade and the beach.",
    description: [
      "This frontline Puerto Banus duplex penthouse is set up for guests who want the marina at their doorstep. The booking page lists 2 bedrooms, 2 bathrooms, 3 double beds and space for 5 guests.",
      "The apartment is positioned for beach days, nightlife, restaurants and designer shopping, with private paid parking and airport transfers available on request through the host.",
      "Guest services noted on the booking page include arrival support, optional extra cleaning, linen change and ironing services. A late check-in fee and weekly cleaning requirement may apply for longer stays.",
    ],
    amenities: ["Beach front", "Free WiFi", "Kitchen", "Air conditioning", "Washing Machine", "Pets allowed"],
    highlights: ["First-line marina position", "Two terraces", "Private parking by request", "Airport transfer option"],
    images: [
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350049-2E2SfOMvTYQ5jepxpP1TaXHhbZHvsOHcJjBL9mv--zdE-678645f58b08c?width=1200&quality=75&format=webp&v=2",
        alt: "Duplex Puerto Banus Penthouse main booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350049-U53atOY88kAsadFL2TsDMfjnfNYt3gS-JERa7UVU9G4-678636947a256?width=1200&quality=75&format=webp&v=2",
        alt: "Duplex Puerto Banus Penthouse interior booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350049-BKx2qAalwT--VGDdvukM7QZQUKSbi0Bym8ga3xBZLKA-6786369149b49?width=1200&quality=75&format=webp&v=2",
        alt: "Duplex Puerto Banus Penthouse terrace or living space booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350049-MnSPVwU1ypDzdz45XBP--vO4Fh--5--2epF5pIR5BDvE2E-6786368ff2ac1?width=1200&quality=75&format=webp&v=2",
        alt: "Duplex Puerto Banus Penthouse additional booking photo",
      },
    ],
  },
  {
    code: "K2",
    slug: "k2-modern-2-bed-frontline-apt",
    path: "properties/k2-modern-2-bed-frontline-apt.html",
    title: "Modern 2 Bed Frontline Apt",
    bookingTitle: "Modern 2 Bed Frontline Apt. Puerto Banus K2",
    type: "Apartment",
    bookingUrl: "https://marbellapuertobanus.holidayfuture.com/listings/350050",
    source: "Direct booking page",
    guests: "4 guests",
    bedrooms: "2 bedrooms",
    bathrooms: "2 bathrooms",
    beds: "2 double beds",
    rating: "4.90",
    reviews: "1 review",
    imageCount: "20 photos",
    summary:
      "A modern first-line Puerto Banus apartment with marina views from the living room and terrace, close to the port, beach, restaurants, bars and shops.",
    description: [
      "The booking page describes this as a modern first-line apartment in Puerto Banus with views over the marina from the living room and terrace.",
      "It is listed with 2 bedrooms, 2 bathrooms, 2 double beds and capacity for 4 guests, with a TV package that includes international channels.",
      "Paid private parking, airport transfers, private drivers and extra guest services can be arranged through the host. Longer stays may require scheduled cleaning.",
    ],
    amenities: ["Beach front", "Free WiFi", "Kitchen", "Air conditioning", "Washing Machine", "Pets allowed"],
    highlights: ["Frontline marina views", "Terrace", "International TV channels", "Parking by request"],
    images: [
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350050-75RkNA5gmqffPW5xa-dUIMyRyfK1Llq6adAWsazF--hY-678645ecd2ed7?width=1200&quality=75&format=webp&v=2",
        alt: "Modern 2 Bed Frontline Apt main booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350050-nCZ013tY2D0jfLBzeuMo3jouL2HOOc8WaGr7G46VHrs-678654ca1703c?width=1200&quality=75&format=webp&v=2",
        alt: "Modern 2 Bed Frontline Apt interior booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350050-cx-k1OKgwymkj-YF3KnUHTNxcIgt1Jmn1WgscNl785c-678636778a5b6?width=1200&quality=75&format=webp&v=2",
        alt: "Modern 2 Bed Frontline Apt additional booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350050-6WQNyVHWIREjQOEujZS7ANNo--tlhWMfAS99B5ZerpRg-67863676543a3?width=1200&quality=75&format=webp&v=2",
        alt: "Modern 2 Bed Frontline Apt gallery booking photo",
      },
    ],
  },
  {
    code: "M2",
    slug: "m2-modern-puerto-banus-frontline-apt",
    path: "properties/m2-modern-puerto-banus-frontline-apt.html",
    title: "Modern Puerto Banus Frontline Apt",
    bookingTitle: "Modern Puerto Banus Frontline Apartment M2",
    type: "Apartment",
    bookingUrl: "https://marbellapuertobanus.holidayfuture.com/listings/350051",
    source: "Direct booking page",
    guests: "4 guests",
    bedrooms: "2 bedrooms",
    bathrooms: "1 bathroom",
    beds: "1 double bed and 2 single beds",
    rating: "4.90",
    reviews: "2 reviews",
    imageCount: "33 photos",
    summary:
      "A modern frontline apartment overlooking Puerto Banus marina from the living room and terrace, arranged for four guests in two bedrooms.",
    description: [
      "This Puerto Banus frontline apartment is listed with 2 bedrooms, 1 bathroom and sleeping space for 4 guests across 1 double bed and 2 single beds.",
      "The booking page highlights marina views from the living room and terrace, plus a location within walking distance of the port, beach, clubs, restaurants and shops.",
      "Guest support includes paid parking by request, airport transfer options, private drivers, extra cleaning and arrival guidance from the host.",
    ],
    amenities: ["Kitchen", "Air conditioning", "Washing Machine", "Street parking", "Suitable for children", "Internet"],
    highlights: ["Frontline marina position", "Terrace views", "Sleeps 4", "Transfer support available"],
    images: [
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350051-rXbIvse7Ktx51dQs5JrJIETSg1ROQ5kHhmnq4ioVkbY-67863660df438?width=1200&quality=75&format=webp&v=2",
        alt: "Modern Puerto Banus Frontline Apt main booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350051-Dc7nluXKYEO6---QsASrJ8KhnG5N9SuIMx0--RP5qqIhk-678636364837b?width=1200&quality=75&format=webp&v=2",
        alt: "Modern Puerto Banus Frontline Apt interior booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350051-O6g8LIUu7yAzvyCd8idd3xniYiKF2rUdI--Vh5X7dKJ0-6786365f5ba0d?width=1200&quality=75&format=webp&v=2",
        alt: "Modern Puerto Banus Frontline Apt gallery booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350051-hjjoSBfHMrY9awu-0i41RALhvmSb4FEXLF0QuY--5QwQ-6786365e0f2d9?width=1200&quality=75&format=webp&v=2",
        alt: "Modern Puerto Banus Frontline Apt additional booking photo",
      },
    ],
  },
  {
    code: "Alvaro",
    slug: "alvaro-new-frontline-sea-view",
    path: "properties/alvaro-new-frontline-sea-view.html",
    title: "New - Frontline - Sea View",
    type: "Rental property",
    source: "CSV row only",
    guests: "To be confirmed",
    bedrooms: "To be confirmed",
    bathrooms: "To be confirmed",
    beds: "To be confirmed",
    imageCount: "Image placeholders",
    summary:
      "The CSV includes this property name but does not include a description, bed count, bath count or booking link yet.",
    description: [
      "Full property description to be added. Use this space for the guest-facing overview, sleeping arrangements, bathroom count, location notes and any booking conditions.",
      "Because no source description was included for this row, beds, baths and guest capacity are intentionally left as placeholders.",
    ],
    amenities: ["Amenity placeholder", "Kitchen placeholder", "WiFi placeholder", "Air conditioning placeholder"],
    highlights: ["Frontline note placeholder", "Sea view note placeholder", "Guest capacity pending"],
    images: [
      { placeholder: "Hero image placeholder" },
      { placeholder: "Living space placeholder" },
      { placeholder: "Bedroom placeholder" },
      { placeholder: "View placeholder" },
    ],
  },
  {
    code: "Yahya",
    slug: "yahya-first-line-amazing-sea-view",
    path: "properties/yahya-first-line-amazing-sea-view.html",
    title: "First-Line w/ Amazing Sea View",
    type: "Rental property",
    source: "CSV row only",
    guests: "To be confirmed",
    bedrooms: "To be confirmed",
    bathrooms: "To be confirmed",
    beds: "To be confirmed",
    imageCount: "Image placeholders",
    summary:
      "The CSV includes this property name but does not include a description, bed count, bath count or booking link yet.",
    description: [
      "Full property description to be added. This page is ready for the first-line sea-view copy, room details, amenities and guest instructions once the source text is available.",
      "Beds, baths and guest capacity are placeholders until a description or booking source is supplied.",
    ],
    amenities: ["Amenity placeholder", "Kitchen placeholder", "WiFi placeholder", "Air conditioning placeholder"],
    highlights: ["First-line note placeholder", "Sea view note placeholder", "Guest capacity pending"],
    images: [
      { placeholder: "Hero image placeholder" },
      { placeholder: "Terrace placeholder" },
      { placeholder: "Bedroom placeholder" },
      { placeholder: "Bathroom placeholder" },
    ],
  },
  {
    code: "Myramar",
    slug: "myramar-edificio-myramar-apartment",
    path: "properties/myramar-edificio-myramar-apartment.html",
    title: "Edificio Myramar Apartment",
    type: "Rental property",
    source: "CSV row only",
    guests: "To be confirmed",
    bedrooms: "To be confirmed",
    bathrooms: "To be confirmed",
    beds: "To be confirmed",
    imageCount: "Image placeholders",
    summary:
      "The CSV includes this property name but does not include a description, bed count, bath count or booking link yet.",
    description: [
      "Full property description to be added. This page can hold the building overview, apartment layout, room count, amenities and arrival notes when the details are ready.",
      "No booking link or description was supplied for this property, so the detail fields remain placeholders.",
    ],
    amenities: ["Amenity placeholder", "Kitchen placeholder", "WiFi placeholder", "Air conditioning placeholder"],
    highlights: ["Building note placeholder", "Location note placeholder", "Guest capacity pending"],
    images: [
      { placeholder: "Hero image placeholder" },
      { placeholder: "Living space placeholder" },
      { placeholder: "Bedroom placeholder" },
      { placeholder: "Exterior placeholder" },
    ],
  },
  {
    code: "Benabola",
    slug: "benabola-puerto-banus-apartment",
    path: "properties/benabola-puerto-banus-apartment.html",
    title: "Puerto Banus Apartment",
    bookingTitle: "Spectacular Puerto Banus Modern 5 Bed Apartment",
    type: "Condominium",
    bookingUrl: "https://marbellapuertobanus.holidayfuture.com/listings/350053",
    source: "Direct booking page",
    guests: "8 guests",
    bedrooms: "5 bedrooms",
    bathrooms: "3 bathrooms",
    beds: "Multiple beds",
    rating: "4.35",
    reviews: "1 review",
    imageCount: "38 photos",
    summary:
      "A modern frontline Puerto Banus apartment with five bedrooms, three bathrooms and spectacular views from a central port location.",
    description: [
      "The linked booking page presents this as a spectacular modern frontline apartment in Puerto Banus with 5 bedrooms, 3 bathrooms and capacity for 8 guests.",
      "It highlights the location close to luxury shops, yachts, restaurants, sports cars and Puerto Banus nightlife, with a parking spot available for guests.",
      "The booking page notes late check-in charges, a longer-stay cleaning policy and optional taxi service for airport and apartment transfers.",
    ],
    amenities: ["Kitchen", "Air conditioning", "Washing Machine", "Suitable for children", "Internet", "Wireless"],
    highlights: ["5 bedrooms", "Frontline Puerto Banus", "Guest parking spot", "Airport taxi service by request"],
    images: [
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350053-pIVr--62VuXEdkNif6dYjCfXpp4--0V7gGFB3kvjP0CL8-6786360b83df2?width=1200&quality=75&format=webp&v=2",
        alt: "Puerto Banus Apartment main booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350053-41cg1n5xCvBhA7NAts7d2H2L8NGdl34hfbpkcdymSYs-678635d7a7e17?width=1200&quality=75&format=webp&v=2",
        alt: "Puerto Banus Apartment interior booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350053-LMivZNOXmLc35pDHPYYe8jw9PvKlWp--ULmhWD8X7Amc-678635db89d76?width=1200&quality=75&format=webp&v=2",
        alt: "Puerto Banus Apartment gallery booking photo",
      },
      {
        src: "https://bookingenginecdn.hostaway.com/listing/137459-350053-y1HDbFy1oCs7DPSZmH8lmEJxUAjdjAwwlkslQ--IsuhY-6786360a2d40a?width=1200&quality=75&format=webp&v=2",
        alt: "Puerto Banus Apartment additional booking photo",
      },
    ],
  },
];
